# default
spring:
  profiles:
    active: dev-local

---
spring:
  profiles: dev-remote
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300

---
spring:
  profiles: dev-local
  data:
    elasticsearch:
      properties:
        http:
          enabled: true

---
spring:
  profiles: test
  data:
    elasticsearch:
      properties:
        http:
          enabled: true
        network.host: 0.0.0.0
